# Ubuntu 18.04
os: linux
dist: bionic

language: cpp

# Command(s) to install dependencies
before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - pyenv global 3.7
  - sudo apt-get update
  - sudo apt-get -y install openmpi-bin openmpi-common openmpi-doc libopenmpi-dev
  - sudo apt-get -y install lcov
  - sudo apt-get -y install gnuplot
  - pip install numpy
  - pip install statsmodels
  - pip install git+https://github.com/snkas/exputilpy.git

# Command(s) to build
install:
  - bash auto-build.sh

# Command(s) to run after the build (which is none)
script:
  - echo "Successfully built"
